language: python
python:
  - '3.6'
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y -qq upgrade
  - sudo apt-get -y install r-base-dev
install: "pip install -r requirements.txt"
script: make travis