language: python
python:
  - '3.6'
notifications:
  email: false
before_install:
  - codename=$(lsb_release -c -s)
  - echo "deb http://cran.fhcrc.org/bin/linux/ubuntu $codename/" | sudo tee -a /etc/apt/sources.list > /dev/null
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository -y ppa:marutter/rdev
  - sudo apt-get update -y
  - sudo apt-get -y install r-base r-base-dev
install: "pip install -r requirements.txt"
script: make travis
# deploy:
#   - provider: s3
#     access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
#     secret_access_key: $AWS_SECRET_KEY
#     bucket: pythonplot.com
#     endpoint: pythonplot.com.s3-website-us-east-1.amazonaws.com
#     region: us-east-1
#     skip_cleanup: true
#     local-dir: web
#     acl: public_read
#     default_text_charset: 'utf-8'
#     detect_encoding: true
#     on:
#       branch: master
